import type { Metadata } from "next";
import "@pigment-css/react/styles.css";
import { DM_Sans } from "next/font/google";
import { css } from "@pigment-css/react";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-dmsans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const htmlClass = css({
  backgroundColor: "var(--c-primary-default)",
  color: "var(--c-primary-light)",
});

const bodyClass = css({
  margin: "0 auto",
  minHeight: "100vh",
  maxWidth: "1560px",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={htmlClass}>
      <body className={`${dmSans.variable} ${bodyClass}`}>{children}</body>
    </html>
  );
}
